export const enum NODE {
  PRODUCTION = 'production',
  DEVELOPMENT = 'development',
}

export const enum ENV {
  GOOGLE_APPLICATION_CREDENTIALS = 'GOOGLE_APPLICATION_CREDENTIALS',
  EXPORT_SPREADSHEET_ID = 'EXPORT_SPREADSHEET_ID',
  ACTUAL_SPREADSHEET_ID = 'ACTUAL_SPREADSHEET_ID',
  EXPORT_SHEET_ID = 'EXPORT_SHEET_ID',
  ARCHIVE_FOLDER = 'ARCHIVE_FOLDER',
  PARENT_FOLDER = 'PARENT_FOLDER',
  SHEETS_SCOPES = 'SHEETS_SCOPES',
  DRIVE_SCOPES = 'DRIVE_SCOPES',
  CAPTCHA_API_TOKEN = 'CAPTCHA_API_TOKEN',
  EXCHANGE_RATE_URL = 'EXCHANGE_RATE_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  LASTUID_REDIS_PATH = 'LASTUID_REDIS_PATH',
  API_TOKEN = 'API_TOKEN',
}

export const enum Queues {
  PARSER = 'PARSER',
  LOGS = 'LOGS',
}
